import streamlit as st
import PyPDF2
import os
import google.generativeai as genai
from dotenv import load_dotenv


# Load environment variables
load_dotenv()

# Configure Gemini API

genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

# Streamlit app UI
st.set_page_config(page_title="Gemini PDF & Text Summarizer", page_icon="🧠")
st.title("🧠 Gemini PDF & Text Summarizer")

st.markdown("Upload a PDF **or** type your text below to get a summary generated by **Google Gemini API**.")

# File uploader or text input
uploaded_file = st.file_uploader("📄 Upload a PDF", type=["pdf"])
text_input = st.text_area("📝 Or paste your text here:")

# Extract text from PDF
text_content = ""
if uploaded_file is not None:
    pdf_reader = PyPDF2.PdfReader(uploaded_file)
    for page in pdf_reader.pages:
        text_content += page.extract_text()

# Prioritize manually entered text
if text_input.strip():
    text_content = text_input.strip()

# Function to summarize using Gemini
def summarize_with_gemini(text):
    model = genai.GenerativeModel("gemini-2.0-flash")
    response = model.generate_content(f"Summarize the following text clearly and concisely:\n\n{text}")
    return response.text.strip()

# Summarize button
if st.button("✨ Summarize"):
    if not text_content.strip():
        st.warning("Please upload a PDF or enter text first.")
    else:
        with st.spinner("Generating summary..."):
            summary = summarize_with_gemini(text_content)
        st.subheader("📑 Summary:")
        st.write(summary)
